CREATE TABLE users (
    user_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    username VARCHAR(50) NOT NULL UNIQUE,
    address VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    wallet VARCHAR(100) NOT NULL
);
